// Everything the installer does to a target project: rendered skills,
// Claude Code links, instruction files, the lock file, and migrations.

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  cpSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  readlinkSync,
  renameSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { CONFIG_FILE, LOCK_FILE, PATH_KEYS, defaultConfig, validateConfig } from "./paths.mjs";
import { REPO_ROOT, renderSkill, resolveSkillSet } from "./render.mjs";

export const AGENTS_SKILLS = ".agents/skills";
export const CLAUDE_SKILLS = ".claude/skills";
const BLOCK_START = "<!-- mattpocock-skills:paths:start -->";
const BLOCK_END = "<!-- mattpocock-skills:paths:end -->";
const IMPORT_LINE = "@AGENTS.md";
const MIGRATION_SKIP_DIRS = new Set([".git", "node_modules", ".agents", ".claude", "vendor"]);

const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");
const readJson = (file) => JSON.parse(readFileSync(file, "utf8"));
const sameConfig = (a, b) => JSON.stringify(a) === JSON.stringify(b);

function exists(path) {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
}

function git(cwd, args) {
  try {
    return execFileSync("git", ["-C", cwd, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return null;
  }
}

export function sourceInfo() {
  const commit = git(REPO_ROOT, ["rev-parse", "HEAD"]);
  const dirty = git(REPO_ROOT, ["status", "--porcelain", "--", "skills", "installer"]);
  return { commit, dirty: dirty === null ? null : dirty.length > 0 };
}

export function loadConfig(root, { createIfMissing, dryRun, log }) {
  const file = join(root, CONFIG_FILE);
  if (!existsSync(file)) {
    if (!createIfMissing) throw new Error(`${CONFIG_FILE} not found in ${root}`);
    log(`${CONFIG_FILE} not found: ${dryRun ? "would write" : "writing"} one with the upstream defaults`);
    if (!dryRun) {
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, `${JSON.stringify(defaultConfig(), null, 2)}\n`);
    }
    return validateConfig(defaultConfig());
  }
  let raw;
  try {
    raw = readJson(file);
  } catch (err) {
    throw new Error(`${CONFIG_FILE} is not valid JSON: ${err.message}`);
  }
  return validateConfig(raw);
}

export function loadLock(root) {
  const file = join(root, LOCK_FILE);
  return existsSync(file) ? readJson(file) : null;
}

export function managedBlock(paths) {
  const rows = Object.entries(PATH_KEYS)
    .filter(([key]) => paths[key] !== null)
    .map(([key, spec]) => {
      const where = spec.scope === "context" ? " (per context)" : "";
      const value = paths[key] === "." ? "the repo root" : `\`${paths[key]}${spec.kind === "dir" ? "/" : ""}\``;
      return `| ${spec.label}${where} | ${value} |`;
    });
  return [
    BLOCK_START,
    "## Artifact locations",
    "",
    `Generated by the skills installer from \`${CONFIG_FILE}\`: edit that file and re-run the installer instead of editing this block. The installed skills (\`${AGENTS_SKILLS}/\`, linked into \`${CLAUDE_SKILLS}/\`) already use these paths. "Per context" paths are relative to each context root, which is the repo root in a single-context project; every other path is relative to the repo root.`,
    "",
    "| Artifact | Path |",
    "|---|---|",
    ...rows,
    BLOCK_END,
  ].join("\n");
}

function upsertBlock(text, block) {
  const start = text.indexOf(BLOCK_START);
  const end = text.indexOf(BLOCK_END);
  if (start !== -1 && end > start) {
    return text.slice(0, start) + block + text.slice(end + BLOCK_END.length);
  }
  const base = text.replace(/\s*$/, "");
  return base ? `${base}\n\n${block}\n` : `${block}\n`;
}

const hasImport = (text) => text.split(/\r?\n/).some((line) => line.trim() === IMPORT_LINE);

export function expectedInstructionFiles(root, paths) {
  const agentsPath = join(root, "AGENTS.md");
  const claudePath = join(root, "CLAUDE.md");
  const agents = existsSync(agentsPath) ? readFileSync(agentsPath, "utf8") : "";
  const claude = existsSync(claudePath) ? readFileSync(claudePath, "utf8") : "";
  const nextClaude = hasImport(claude)
    ? claude
    : claude.trim()
      ? `${claude.replace(/\s*$/, "")}\n\n${IMPORT_LINE}\n`
      : `${IMPORT_LINE}\n`;
  return [
    { path: agentsPath, before: agents, after: upsertBlock(agents, managedBlock(paths)) },
    { path: claudePath, before: claude, after: nextClaude },
  ];
}

// ---------------------------------------------------------------- migration

function walkDirs(root, dir = root, out = [root]) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory() || MIGRATION_SKIP_DIRS.has(entry.name)) continue;
    const full = join(dir, entry.name);
    out.push(full);
    walkDirs(root, full, out);
  }
  return out;
}

function isKind(path, kind) {
  try {
    const st = lstatSync(path);
    return kind === "dir" ? st.isDirectory() : st.isFile();
  } catch {
    return false;
  }
}

// Moves needed to bring existing artifacts from `oldPaths` to `newPaths`.
export function planMigration(root, oldPaths, newPaths) {
  const moves = [];
  const problems = [];
  const contextRoots = walkDirs(root);
  for (const [key, spec] of Object.entries(PATH_KEYS)) {
    const from = oldPaths[key];
    const to = newPaths[key];
    if (from === to || from === null || to === null) continue;
    if (key === "teachDir") {
      if (existsSync(join(root, from === "." ? "MISSION.md" : from))) {
        problems.push(`teachDir changed (${from} -> ${to}): move the teaching workspace by hand`);
      }
      continue;
    }
    const bases = spec.scope === "context" ? contextRoots : [root];
    for (const base of bases) {
      const src = join(base, from);
      if (!isKind(src, spec.kind)) continue;
      const dest = join(base, to);
      if (exists(dest)) {
        problems.push(`${relative(root, src)} -> ${relative(root, dest)}: destination already exists`);
        continue;
      }
      moves.push({ key, src, dest });
    }
  }
  return { moves, problems };
}

function pathTokenRegex(value) {
  const escaped = value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`(?<![\\w.-])${escaped}(?![\\w-])`, "g");
}

// Rewrites references to moved paths in the files that hold them: the
// instruction files, the skills config written by /setup-matt-pocock-skills,
// and the context map.
export function planReferenceRewrites(root, oldPaths, newPaths) {
  const candidates = [join(root, "AGENTS.md"), join(root, "CLAUDE.md"), join(root, newPaths.contextMap)];
  const configDir = join(root, newPaths.skillsConfigDir);
  const oldConfigDir = join(root, oldPaths.skillsConfigDir);
  for (const dir of [configDir, oldConfigDir]) {
    if (isKind(dir, "dir")) {
      for (const f of readdirSync(dir)) if (f.endsWith(".md")) candidates.push(join(dir, f));
    }
  }
  const changed = Object.keys(PATH_KEYS).filter(
    (k) => k !== "teachDir" && oldPaths[k] !== newPaths[k] && oldPaths[k] !== null && newPaths[k] !== null,
  );
  const rewrites = [];
  for (const file of new Set(candidates)) {
    if (!isKind(file, "file")) continue;
    const before = readFileSync(file, "utf8");
    let after = before;
    for (const key of changed) after = after.replace(pathTokenRegex(oldPaths[key]), newPaths[key]);
    if (after !== before) rewrites.push({ file, before, after });
  }
  return rewrites;
}

function moveArtifact(root, src, dest) {
  mkdirSync(dirname(dest), { recursive: true });
  const tracked = git(root, ["ls-files", "--", relative(root, src)]);
  if (tracked) {
    execFileSync("git", ["-C", root, "mv", relative(root, src), relative(root, dest)], { stdio: "ignore" });
  } else {
    renameSync(src, dest);
  }
}

// ---------------------------------------------------------------- install

function removeSkill(root, name) {
  rmSync(join(root, AGENTS_SKILLS, name), { recursive: true, force: true });
  const claude = join(root, CLAUDE_SKILLS, name);
  if (exists(claude)) rmSync(claude, { recursive: true, force: true });
}

function writeRendered(target, files) {
  rmSync(target, { recursive: true, force: true });
  for (const { rel, content, mode } of files) {
    const out = join(target, ...rel.split("/"));
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, content, { mode });
  }
}

function linkTarget(name) {
  return ["..", "..", ...AGENTS_SKILLS.split("/"), name].join("/");
}

export function install(root, opts) {
  const {
    dryRun = false,
    migrate = false,
    skipMigration = false,
    force = false,
    claudeCopy = false,
    log = console.log,
  } = opts;
  const act = (msg, fn) => {
    log(`${dryRun ? "[dry-run] " : ""}${msg}`);
    if (!dryRun) fn();
  };

  const config = loadConfig(root, { createIfMissing: true, dryRun, log });
  const lock = loadLock(root);
  const skills = resolveSkillSet(config.extraSkills);
  const owned = new Set(Object.keys(lock?.skills ?? {}));
  const claudeMode = claudeCopy ? "copy" : "symlink";

  // Refuse to clobber skills this installer did not put there.
  const conflicts = [];
  for (const { name } of skills) {
    if (owned.has(name)) continue;
    for (const base of [AGENTS_SKILLS, CLAUDE_SKILLS]) {
      if (exists(join(root, base, name))) conflicts.push(`${base}/${name}`);
    }
  }
  if (conflicts.length && !force) {
    throw new Error(
      `these skill folders exist but were not installed by this installer:\n  ${conflicts.join("\n  ")}\nre-run with --force to replace them`,
    );
  }

  // Artifacts at the previous locations.
  if (lock && !sameConfig(lock.config.paths, config.paths)) {
    const { moves, problems } = planMigration(root, lock.config.paths, config.paths);
    const rewrites = planReferenceRewrites(root, lock.config.paths, config.paths);
    if (!migrate) {
      // The lock is about to forget the old locations, so stop rather than
      // silently leave artifacts behind.
      if ((moves.length || rewrites.length) && !skipMigration) {
        const lines = [
          ...moves.map((m) => `${relative(root, m.src)} -> ${relative(root, m.dest)}`),
          ...rewrites.map((r) => `references in ${relative(root, r.file)}`),
        ];
        throw new Error(
          `paths changed since the last install and existing artifacts still use the old locations:\n  ${lines.join("\n  ")}\nre-run with --migrate to move them, or --skip-migration to leave them where they are`,
        );
      }
    } else {
      if (problems.length) {
        throw new Error(`cannot migrate:\n  ${problems.join("\n  ")}`);
      }
      for (const m of moves) {
        act(`move ${relative(root, m.src)} -> ${relative(root, m.dest)}`, () => moveArtifact(root, m.src, m.dest));
      }
      // Re-plan after the moves so rewrites see files at their new homes.
      const finalRewrites = dryRun ? rewrites : planReferenceRewrites(root, lock.config.paths, config.paths);
      for (const r of finalRewrites) {
        act(`update path references in ${relative(root, r.file)}`, () => writeFileSync(r.file, r.after));
      }
    }
  }

  for (const name of owned) {
    if (!skills.some((s) => s.name === name)) {
      act(`remove skill ${name}`, () => removeSkill(root, name));
    }
  }

  const lockSkills = {};
  for (const { name, dir } of skills) {
    const { files } = renderSkill(name, dir, config.paths);
    lockSkills[name] = { files: Object.fromEntries(files.map((f) => [f.rel, sha256(f.content)])) };
    const target = join(root, AGENTS_SKILLS, name);
    act(`write ${AGENTS_SKILLS}/${name}`, () => writeRendered(target, files));
    const claudePath = join(root, CLAUDE_SKILLS, name);
    act(`${claudeMode === "copy" ? "copy" : "link"} ${CLAUDE_SKILLS}/${name}`, () => {
      rmSync(claudePath, { recursive: true, force: true });
      mkdirSync(dirname(claudePath), { recursive: true });
      if (claudeMode === "copy") cpSync(target, claudePath, { recursive: true });
      else symlinkSync(linkTarget(name), claudePath, "dir");
    });
  }

  for (const f of expectedInstructionFiles(root, config.paths)) {
    if (f.before !== f.after) {
      act(`update ${relative(root, f.path)}`, () => writeFileSync(f.path, f.after));
    }
  }

  const nextLock = {
    generatedBy: "installer/install.mjs",
    source: sourceInfo(),
    config,
    claudeSkills: claudeMode,
    skills: lockSkills,
  };
  act(`write ${LOCK_FILE}`, () => writeFileSync(join(root, LOCK_FILE), `${JSON.stringify(nextLock, null, 2)}\n`));
  return nextLock;
}

// ---------------------------------------------------------------- check

function filesUnder(dir) {
  const out = [];
  const walk = (d) => {
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const full = join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else out.push(relative(dir, full).split(sep).join("/"));
    }
  };
  walk(dir);
  return out.sort();
}

// Verifies a project against its lock file without needing the skill
// sources, so it can run in the project's own CI. Returns a list of problems.
export function check(root) {
  const problems = [];
  const lock = loadLock(root);
  if (!lock) return [`${LOCK_FILE} not found: run the installer first`];
  let config;
  try {
    config = loadConfig(root, { createIfMissing: false });
  } catch (err) {
    return [err.message];
  }
  if (!sameConfig(config, lock.config)) {
    problems.push(`${CONFIG_FILE} changed since the last install: re-run the installer`);
  }
  for (const [name, { files }] of Object.entries(lock.skills)) {
    const dir = join(root, AGENTS_SKILLS, name);
    if (!isKind(dir, "dir")) {
      problems.push(`${AGENTS_SKILLS}/${name} is missing`);
      continue;
    }
    const onDisk = filesUnder(dir);
    for (const rel of onDisk) {
      if (!(rel in files)) problems.push(`${AGENTS_SKILLS}/${name}/${rel} is not part of the install`);
      else if (sha256(readFileSync(join(dir, rel))) !== files[rel]) {
        problems.push(`${AGENTS_SKILLS}/${name}/${rel} was edited by hand`);
      }
    }
    for (const rel of Object.keys(files)) {
      if (!onDisk.includes(rel)) problems.push(`${AGENTS_SKILLS}/${name}/${rel} is missing`);
    }
    const claudePath = join(root, CLAUDE_SKILLS, name);
    if (lock.claudeSkills === "symlink") {
      let ok = false;
      try {
        ok = lstatSync(claudePath).isSymbolicLink() && readlinkSync(claudePath) === linkTarget(name);
      } catch {}
      if (!ok) problems.push(`${CLAUDE_SKILLS}/${name} should be a symlink to ${linkTarget(name)}`);
    } else if (!isKind(claudePath, "dir") || filesUnder(claudePath).join() !== onDisk.join()) {
      problems.push(`${CLAUDE_SKILLS}/${name} does not match ${AGENTS_SKILLS}/${name}`);
    } else {
      for (const rel of onDisk) {
        if (!readFileSync(join(claudePath, rel)).equals(readFileSync(join(dir, rel)))) {
          problems.push(`${CLAUDE_SKILLS}/${name}/${rel} differs from ${AGENTS_SKILLS}/${name}/${rel}`);
        }
      }
    }
  }
  for (const f of expectedInstructionFiles(root, lock.config.paths)) {
    if (f.before !== f.after) {
      problems.push(`${relative(root, f.path)} is missing the installer's content: re-run the installer`);
    }
  }
  return problems;
}
